### ISSUE TITLE
I found a bug? "thread 'worker3' panicked at 'index out of bounds: the len is 3 but the index is 3'

### ISSUE THREAD

**Issue by biluohc** [redis-rs/redis-rs#190]
# panicked at 'index out of bounds

There are many such logs when the paniked may occur: `Invalid response when parsing multi response`.

Probably at https://github.com/mitsuhiko/redis-rs/blob/master/src/cmd.rs#L446

versions: redis 0.9.1,  r2d2 0.8.3,  r2d2_redis 0.8.0 

log: 
```json
{"log":"2019-03-04 20:21:32.933 [spark_kvdb::storage] [ERROR][worker3][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response\n","stream":"stdout","time":"2019-03-04T12:21:32.933408413Z"}
{"log":"thread 'worker3' panicked at 'index out of bounds: the len is 3 but the index is 3', /checkout/src/libcore/slice/mod.rs:2051:10\n","stream":"stderr","time":"2019-03-04T12:21:32.940962932Z"}
{"log":"note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n","stream":"stderr","time":"2019-03-04T12:21:32.969313474Z"}
{"log":"stack backtrace:\n","stream":"stderr","time":"2019-03-04T12:21:32.969341827Z"}
{"log":"   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace\n","stream":"stderr","time":"2019-03-04T12:21:32.969345474Z"}
{"log":"             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49\n","stream":"stderr","time":"2019-03-04T12:21:32.971891008Z"}
{"log":"   1: std::sys_common::backtrace::print\n","stream":"stderr","time":"2019-03-04T12:21:32.971901335Z"}
{"log":"             at libstd/sys_common/backtrace.rs:71\n","stream":"stderr","time":"2019-03-04T12:21:32.972959338Z"}
{"log":"             at libstd/sys_common/backtrace.rs:59\n","stream":"stderr","time":"2019-03-04T12:21:32.972966224Z"}
{"log":"   2: std::panicking::default_hook::{{closure}}\n","stream":"stderr","time":"2019-03-04T12:21:32.972969368Z"}
{"log":"             at libstd/panicking.rs:211\n","stream":"stderr","time":"2019-03-04T12:21:32.974264357Z"}
{"log":"   3: std::panicking::default_hook\n","stream":"stderr","time":"2019-03-04T12:21:32.974307083Z"}
{"log":"             at libstd/panicking.rs:227\n","stream":"stderr","time":"2019-03-04T12:21:32.974311028Z"}
{"log":"   4: std::panicking::rust_panic_with_hook\n","stream":"stderr","time":"2019-03-04T12:21:32.974313946Z"}
{"log":"             at libstd/panicking.rs:463\n","stream":"stderr","time":"2019-03-04T12:21:32.974316701Z"}
{"log":"   5: std::panicking::begin_panic_fmt\n","stream":"stderr","time":"2019-03-04T12:21:32.974319564Z"}
{"log":"             at libstd/panicking.rs:350\n","stream":"stderr","time":"2019-03-04T12:21:32.974322349Z"}
{"log":"   6: rust_begin_unwind\n","stream":"stderr","time":"2019-03-04T12:21:32.974325079Z"}
{"log":"             at libstd/panicking.rs:328\n","stream":"stderr","time":"2019-03-04T12:21:32.974327766Z"}
{"log":"   7: core::panicking::panic_fmt\n","stream":"stderr","time":"2019-03-04T12:21:32.974330542Z"}
{"log":"             at libcore/panicking.rs:71\n","stream":"stderr","time":"2019-03-04T12:21:32.975205349Z"}
{"log":"   8: core::panicking::panic_bounds_check\n","stream":"stderr","time":"2019-03-04T12:21:32.975221421Z"}
{"log":"             at libcore/panicking.rs:58\n","stream":"stderr","time":"2019-03-04T12:21:32.975224944Z"}
{"log":"   9: redis::cmd::Pipeline::make_pipeline_results\n","stream":"stderr","time":"2019-03-04T12:21:32.975227918Z"}
{"log":"  10: redis::cmd::Pipeline::execute_transaction\n","stream":"stderr","time":"2019-03-04T12:21:32.975230732Z"}
{"log":"  11: spark_kvdb::storage::\u003cimpl spark_kvdb::Storage for spark_kvdb::redis::Redis\u003e::save_share\n","stream":"stderr","time":"2019-03-04T12:21:32.975233562Z"}
{"log":"  12: spark_bin_server::stratum::StratumRpc::submit_work\n","stream":"stderr","time":"2019-03-04T12:21:32.975237367Z"}
{"log":"  13: \u003cfutures::future::lazy::Lazy\u003cF, R\u003e as futures::future::Future\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975325385Z"}
{"log":"  14: \u003cfutures::future::map::Map\u003cA, F\u003e as futures::future::Future\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975333129Z"}
{"log":"  15: \u003cfutures::future::chain::Chain\u003cA, B, C\u003e\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975336443Z"}
{"log":"  16: \u003cfutures::stream::and_then::AndThen\u003cS, F, U\u003e as futures::stream::Stream\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975339555Z"}
{"log":"  17: \u003cspark_bin_server::peer::PeerMessageQueue\u003cS\u003e as futures::stream::Stream\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975342646Z"}
{"log":"  18: \u003cfutures::sink::send_all::SendAll\u003cT, U\u003e as futures::future::Future\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975364012Z"}
{"log":"  19: \u003cfutures::future::chain::Chain\u003cA, B, C\u003e\u003e::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975370466Z"}
{"log":"  20: \u003cfutures::task_impl::Spawn\u003cT\u003e\u003e::poll_future_notify\n","stream":"stderr","time":"2019-03-04T12:21:32.975375647Z"}
{"log":"  21: \u003cstd::thread::local::LocalKey\u003cT\u003e\u003e::with\n","stream":"stderr","time":"2019-03-04T12:21:32.97538504Z"}
{"log":"  22: \u003ctokio_current_thread::scheduler::Scheduler\u003cU\u003e\u003e::tick\n","stream":"stderr","time":"2019-03-04T12:21:32.975412732Z"}
{"log":"  23: \u003cscoped_tls::ScopedKey\u003cT\u003e\u003e::set\n","stream":"stderr","time":"2019-03-04T12:21:32.975417086Z"}
{"log":"  24: \u003cstd::thread::local::LocalKey\u003cT\u003e\u003e::with\n","stream":"stderr","time":"2019-03-04T12:21:32.975462462Z"}
{"log":"  25: tokio_reactor::with_default\n","stream":"stderr","time":"2019-03-04T12:21:32.975481274Z"}
{"log":"  26: tokio_core::reactor::Core::poll\n","stream":"stderr","time":"2019-03-04T12:21:32.975486518Z"}
{"log":"  27: tokio_core::reactor::Core::run\n","stream":"stderr","time":"2019-03-04T12:21:32.975491133Z"}
{"log":"  28: spark_bin_server::proto::serve\n","stream":"stderr","time":"2019-03-04T12:21:32.975510407Z"}
```

**Comment by badboy** [comment]
Can you provide a minimal sample code to reproduce this panic?
I suspect it's actually in your user code and not in redis-rs.

(and also it would be nice to have only the error output, and not all the surrounding log formatting of your log system, that makes it rather hard to read)

**Comment by biluohc** [comment]
Sorry, this is the log recorded by docker. In fact, it is mainly rust's own backtrace(RUST_BACKTRACE=1). Judging from backtrace, you can found 'Redis:: CMD:: Pipeline:: Make _ Pipeline _ Results',  and above it is' Core', so this' Panicked' should not be my own problem.
 
As for the minimum code reproduction, I'm sorry I failed in my attempt to reproduce it. It only appear on one of many nodes on the product, but my side is all container deployed.

The following is the log without docker format：
```sh
2019-03-04 20:21:23.513 [spark_bin_server::stratum] [INFO][worker4][spark-bin-server/src/stratum.rs:329]  miner login, addr: 140.116.57.201:52528, wallet: 34faaa028162c4d4e92db6abfa236a8e90ff2fc3, id: eth1.0
2019-03-04 20:21:30.204 [spark_kvdb::storage] [ERROR][worker4][spark-kvdb/src/storage.rs:136]  save_share query fail operation would block
2019-03-04 20:21:30.204 [process-share] [ERROR][worker4][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x1f82d02408ad0b6e, for (addr: 36.234.70.9:60523, wallet: af851853a66eba4f0544178a00846cba12ac6b1f, id: "yoyo05")
2019-03-04 20:21:30.204 [r2d2] [ERROR][worker1][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.204 [r2d2] [ERROR][worker14][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.204 [r2d2] [ERROR][worker5][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.204 [r2d2] [ERROR][worker7][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.204 [spark_kvdb::storage] [ERROR][worker2][spark-kvdb/src/storage.rs:136]  save_share query fail operation would block
2019-03-04 20:21:30.204 [process-share] [ERROR][worker2][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x752ad4401770bf66, for (addr: 61.218.197.34:33524, wallet: 2ca7b93e9825dd1f12114d158986011cadd4c347, id: "70363")
2019-03-04 20:21:30.204 [r2d2] [ERROR][worker3][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.329 [spark_bin_server::server] [INFO][worker-wc][spark-bin-server/src/server.rs:102]  worker-count 16 >= 16
2019-03-04 20:21:30.716 [r2d2] [ERROR][worker10][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.972 [r2d2] [ERROR][worker8][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:30.972 [spark_kvdb::storage] [ERROR][worker9][spark-kvdb/src/storage.rs:136]  save_share query fail operation would block
2019-03-04 20:21:30.972 [process-share] [ERROR][worker9][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0xddb518c01203eab4, for (addr: 111.243.197.164:60233, wallet: 81e3ca02b9802e62d2dca98090175e3084522898, id: "wing-574-12-m-h-H19")
2019-03-04 20:21:31.484 [spark_kvdb::storage] [ERROR][worker11][spark-kvdb/src/storage.rs:232]  save_share fail operation would block
2019-03-04 20:21:31.484 [process-share] [ERROR][worker11][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x22ba17a81143c335, for (addr: 180.217.83.89:57283, wallet: b1ed380e3947f38ae54020531d39aec02d3ba218, id: "ETH017")
2019-03-04 20:21:32.764 [spark_kvdb::storage] [ERROR][worker12][spark-kvdb/src/storage.rs:136]  save_share query fail operation would block
2019-03-04 20:21:32.764 [process-share] [ERROR][worker12][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x81145ea560a2e0a1, for (addr: 61.228.182.178:50900, wallet: 205489dc7705680145a4b954857a317ee5a5ebc7, id: "146")
2019-03-04 20:21:32.764 [r2d2] [ERROR][worker0][/usr/local/cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/r2d2-0.8.3/src/lib.rs:116]  operation would block: operation would block
2019-03-04 20:21:32.764 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:136]  save_share query fail operation would block
2019-03-04 20:21:32.764 [process-share] [ERROR][worker13][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0xb459594010eef533, for (addr: 118.166.176.79:50495, wallet: 6a27f333a4dc5374b50ebe654a57edda17b8281e, id: "zebra037Saunt")
2019-03-04 20:21:32.764 [spark_kvdb::storage] [ERROR][worker6][spark-kvdb/src/storage.rs:232]  save_share fail operation would block
2019-03-04 20:21:32.764 [process-share] [ERROR][worker6][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("operation would block"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x656a8b701216a9c9, for (addr: 59.125.83.55:59362, wallet: b13151fc1b08dde08c9226fbaa0e9952cf269858, id: "S-018")
2019-03-04 20:21:32.926 [spark_kvdb::storage] [ERROR][worker11][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:32.932 [spark_kvdb::storage] [ERROR][worker4][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:32.933 [spark_kvdb::storage] [ERROR][worker3][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
thread 'worker3' panicked at 'index out of bounds: the len is 3 but the index is 3', /checkout/src/libcore/slice/mod.rs:2051:10
2019-03-04 20:21:32.959 [spark_kvdb::storage] [ERROR][worker6][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:32.960 [spark_kvdb::storage] [ERROR][worker12][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:32.960 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:32.960 [spark_kvdb::storage] [ERROR][worker12][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
   9: redis::cmd::Pipeline::make_pipeline_results
  10: redis::cmd::Pipeline::execute_transaction
  11: spark_kvdb::storage::<impl spark_kvdb::Storage for spark_kvdb::redis::Redis>::save_share
  12: spark_bin_server::stratum::StratumRpc::submit_work
  13: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  14: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  15: <futures::future::chain::Chain<A, B, C>>::poll
  16: <futures::stream::and_then::AndThen<S, F, U> as futures::stream::Stream>::poll
  17: <spark_bin_server::peer::PeerMessageQueue<S> as futures::stream::Stream>::poll
  18: <futures::sink::send_all::SendAll<T, U> as futures::future::Future>::poll
  19: <futures::future::chain::Chain<A, B, C>>::poll
  20: <futures::task_impl::Spawn<T>>::poll_future_notify
  21: <std::thread::local::LocalKey<T>>::with
  22: <tokio_current_thread::scheduler::Scheduler<U>>::tick
  23: <scoped_tls::ScopedKey<T>>::set
  24: <std::thread::local::LocalKey<T>>::with
  25: tokio_reactor::with_default
  26: tokio_core::reactor::Core::poll
  27: tokio_core::reactor::Core::run
  28: spark_bin_server::proto::serve
2019-03-04 20:21:33.162 [spark_kvdb::storage] [ERROR][worker12][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.162 [process-share] [ERROR][worker12][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0xa86df0601a6397f3, for (addr: 61.218.197.34:64479, wallet: 2ca7b93e9825dd1f12114d158986011cadd4c347, id: "70912")
2019-03-04 20:21:33.162 [spark_kvdb::storage] [ERROR][worker6][spark-kvdb/src/storage.rs:136]  save_share query fail Response was of incompatible type: "Bulk response of wrong dimension" (response was bulk(ok))
2019-03-04 20:21:33.162 [process-share] [ERROR][worker6][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Response was of incompatible type"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x2f6f73101db333f7, for (addr: 1.175.170.7:40808, wallet: 8fb27d742c572d10de775d4a272b157f4eb48569, id: "b2_5")
2019-03-04 20:21:33.162 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.162 [process-share] [ERROR][worker13][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0xec6458f41060aa31, for (addr: 1.165.85.176:41198, wallet: cafcf76c2eebf39056b669653871653cd8f1afa9, id: "sds042")
2019-03-04 20:21:33.162 [spark_kvdb::storage] [ERROR][worker6][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:33.258 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.258 [process-share] [ERROR][worker13][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x17df08941c4d08e3, for (addr: 1.165.85.176:41198, wallet: cafcf76c2eebf39056b669653871653cd8f1afa9, id: "sds042")
2019-03-04 20:21:33.258 [spark_kvdb::storage] [ERROR][worker8][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.258 [process-share] [ERROR][worker8][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x5a7a141816fe724d, for (addr: 114.25.169.142:49980, wallet: 2431b37ca9f516aad592a2aa4aca4f4532b78bff, id: "TB1-104-12-0640")
2019-03-04 20:21:33.261 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:33.262 [spark_kvdb::storage] [ERROR][worker8][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:33.263 [spark_kvdb::storage] [ERROR][worker10][spark-kvdb/src/storage.rs:136]  save_share query fail Response was of incompatible type: "Bulk response of wrong dimension" (response was bulk(ok))
2019-03-04 20:21:33.263 [process-share] [ERROR][worker10][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Response was of incompatible type"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x1af97848191fec73, for (addr: 61.230.47.179:49702, wallet: 72f1e4f0ac3a6f745a0c8607bfe360b97eb4df93, id: "VMonster")
2019-03-04 20:21:33.264 [spark_kvdb::storage] [ERROR][worker13][spark-kvdb/src/storage.rs:67]  save_share set new_epoch fail Invalid response when parsing multi response
2019-03-04 20:21:33.273 [spark_kvdb::storage] [ERROR][worker1][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.273 [process-share] [ERROR][worker1][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0xf0bd602821f4ff5a, for (addr: 114.25.169.142:59908, wallet: 2431b37ca9f516aad592a2aa4aca4f4532b78bff, id: "TB1-104-12-0674")
2019-03-04 20:21:33.275 [spark_kvdb::storage] [ERROR][worker6][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.275 [process-share] [ERROR][worker6][spark-bin-server/src/stratum.rs:535]  save share failed(will reject): Redis("Invalid response when parsing multi response"), height: 7302905, pow-hash: 0xe9ffc09539610eb1843822693281dd344123a278d3f083ea300dc04527d4dc67, nonce: 0x81d2cb000d7ea1f0, for (addr: 180.177.130.211:30339, wallet: 16a8dc8d22743f33da9e53906cd50f18571f3d5a, id: "A4-rx570")
2019-03-04 20:21:33.280 [spark_kvdb::storage] [ERROR][worker8][spark-kvdb/src/storage.rs:136]  save_share query fail Invalid response when parsing multi response
2019-03-04 20:21:33.280 [process-share] [ERROR][worker8][spark-bin-server/src/stratum.rs:535]  save sha
```

**Comment by badboy** [comment]
You are right, it looks like this is a potential bug in redis-rs.
Needs further investigation why this happens.

**Comment by badboy** [comment]
So I looked at the code once more. It's [this code](https://github.com/mitsuhiko/redis-rs/blob/37f5c8c1e54e71bf96869066eac6efd34f94257b/src/cmd.rs#L522-L524) that's panicking.

I would expect our commands to always match up with the responses, but apparently it didn't in this case.
Do you happen to know what kind of commands were run or even exactly which?

**Comment by biluohc** [comment]
There are many transctions in the code,  like the follow code(It is one of them), contains some operation for String and Set.

```rust
redis::pipe()
                .atomic()
                .cmd("SADD")
                .arg(STATS_EPOCH_SET)
                .arg(epoch)
                .ignore()
                .cmd("SET")
                .arg(CURRENT_EPOCH)
                .arg(epoch)
                .query(conn)
```

**Comment by badboy** [comment]
Thanks, maybe that helps identifying a problem.

**Comment by biluohc** [comment]
There seems to be no progress.
So you can add a length judgment before iterating, maybe get the wrong number of values when the redis's connection is abnormal?  Which is not a big overhead.

https://github.com/mitsuhiko/redis-rs/blob/master/src/cmd.rs#L530
```rs
    fn make_pipeline_results(&self, resp: Vec<Value>) -> Value {
        let mut rv = vec![];
        //  if resp.len() > self.commands.len() {
        //    return Err((ErrorKind::ResponseError, ""))
        // }

        for (idx, result) in resp.into_iter().enumerate() {
            if !self.commands[idx].is_ignored {
                rv.push(result);
            }
        }
        Value::Bulk(rv)
    }
```

**Comment by badboy** [comment]
@biluohc Do you have a minimal example to reproduce this?

**Comment by biluohc** [comment]
Sorry, I don't have a minimal example of recurrence, but the stack trace is indeed panic here. 
This kind of problem does not appear again in the product environment because I modified the above code

If you really want to reproduce, maybe simulate a redis server, and it return the wrong response for pipeline.

**Comment by badboy** [comment]
I mean sure, if I simulate wrong responses I can produce weird problems.
And you're above proposed fix might catch that one.
If you send above proposed patch as a PR we'll see what CI thinks about it.

But that's hardly a fix for what seemed to occur in a regular instance of Redis, so I'd like to understand what's happening.

**Comment by biluohc** [comment]
Indeed, this patch may not solve the most fundamental problem.
This patch should have no problem through ci, mainly depends on the opinion of the maintainer.

Perhaps we should not assume that redis will not produce erroneous responses. Users may use it to connect to various servers that implement the resp protocol.
However, we may generate an error rather than panic the thread directly if the server returns an error response.
But I am not sure what is written in the error message.

**Comment by nihohit** [comment]
@biluohc do you still see this issue?

**Comment by NikosZampelis** [comment]
@nihohit I am following this issue as I might be in a similar situation. Do you think it could have been solved in 0.23.3 ? Thank you!

**Comment by nihohit** [comment]
@NikosZampelis can you please post a code snippet, or better - a test?

**Comment by nihohit** [comment]
closing due to inactivity.
