### ISSUE TITLE
panic when reconnect: Multiplexed connection driver unexpectedly terminated

### ISSUE THREAD

**Issue by gensmusic** [redis-rs/redis-rs#563]
Steps:

1.  copy examples https://github.com/mitsuhiko/redis-rs/blob/d4dfd43a0f8ea87319fc5f064fae6930550c4c4e/examples/async-connection-loss.rs into a new cargo project main.rs
2. change  [   let mut interval = interval(Duration::from_millis(100));](https://github.com/mitsuhiko/redis-rs/blob/d4dfd43a0f8ea87319fc5f064fae6930550c4c4e/examples/async-connection-loss.rs#L36) to `let mut interval = interval(Duration::from_millis(1))`,  100->1
3. start redis
3. `RUST_BACKTRACE=1  cargo run reconnect`
4. then stop redis, will get the panic

and  Cargo.toml is

```toml
[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
redis = { version = "0.21", features = ["connection-manager","tokio-comp"] }

```

the panic

```

> PING
> PING
> PING
thread 'main' panicked at 'internal error: entered unreachable code: Multiplexed connection driver unexpectedly terminated', /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/aio.rs:891:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
   2: redis::aio::MultiplexedConnection::new::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/aio.rs:891:21
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
   4: redis::client::Client::create_multiplexed_async_connection_inner::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/client.rs:238:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
   6: redis::client::Client::get_multiplexed_async_connection_inner::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/client.rs:221:36
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
   8: redis::client::Client::get_multiplexed_tokio_connection::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/client.rs:141:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  10: redis::client::Client::get_multiplexed_async_connection::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/client.rs:126:31
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  12: redis::aio::connection_manager::ConnectionManager::reconnect::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/aio.rs:1032:33
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/future.rs:119:9
  15: <futures_util::future::future::shared::Shared<Fut> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/future/shared.rs:287:19
  16: <redis::aio::connection_manager::ConnectionManager as redis::aio::ConnectionLike>::req_packed_command::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/aio.rs:1079:41
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/future.rs:119:9
  19: redis::cmd::Cmd::query_async::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/redis-0.21.4/src/cmd.rs:377:19
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  21: <futures_util::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/maybe_done.rs:95:38
  22: <futures_util::future::join::Join3<Fut1,Fut2,Fut3> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/join.rs:55:33
  23: redis_test::run_multi::{{closure}}
             at ./src/main.rs:47:13
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  25: redis_test::main::{{closure}}
             at ./src/main.rs:84:28
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  27: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/park/thread.rs:263:54
  28: tokio::coop::with_budget::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:106:9
  29: std::thread::local::LocalKey<T>::try_with
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  30: std::thread::local::LocalKey<T>::with
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  31: tokio::coop::with_budget
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:99:5
  32: tokio::coop::budget
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:76:5
  33: tokio::park::thread::CachedParkThread::block_on
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/park/thread.rs:263:31
  34: tokio::runtime::enter::Enter::block_on
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/enter.rs:151:13
  35: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/mod.rs:77:9
  36: tokio::runtime::Runtime::block_on
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/mod.rs:463:43
  37: redis_test::main
             at ./src/main.rs:86:5
  38: core::ops::function::FnOnce::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tokio-runtime-worker' panicked at 'inner future panicked during poll', /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/future/shared.rs:258:25
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:543:12
   1: <futures_util::future::future::shared::Shared<Fut> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/future/shared.rs:258:25
   2: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/future/future/map.rs:55:37
   3: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.18/src/lib.rs:95:13
   4: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/core.rs:161:17
   5: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/loom/std/unsafe_cell.rs:14:9
   6: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/core.rs:151:13
   7: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:461:19
   8: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
   9: std::panicking::try::do_call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  10: <unknown>
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.0/src/raw/bitmask.rs:26:6
  11: std::panicking::try
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  12: std::panic::catch_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  13: tokio::runtime::task::harness::poll_future
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:449:18
  14: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:98:27
  15: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:53:15
  16: tokio::runtime::task::raw::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/raw.rs:113:5
  17: tokio::runtime::task::raw::RawTask::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/raw.rs:70:18
  18: tokio::runtime::task::LocalNotified<S>::run
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/mod.rs:343:9
  19: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:420:13
  20: tokio::coop::with_budget::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:106:9
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  22: std::thread::local::LocalKey<T>::with
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  23: tokio::coop::with_budget
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:99:5
  24: tokio::coop::budget
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/coop.rs:76:5
  25: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:419:9
  26: tokio::runtime::thread_pool::worker::Context::run
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:386:24
  27: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:371:17
  28: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/macros/scoped_tls.rs:61:9
  29: tokio::runtime::thread_pool::worker::run
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:368:5
  30: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/thread_pool/worker.rs:347:45
  31: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/blocking/task.rs:42:21
  32: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/core.rs:161:17
  33: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/loom/std/unsafe_cell.rs:14:9
  34: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/core.rs:151:13
  35: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:461:19
  36: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
  37: std::panicking::try::do_call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  38: <unknown>
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:438:2
  39: std::panicking::try
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  40: std::panic::catch_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  41: tokio::runtime::task::harness::poll_future
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:449:18
  42: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:98:27
  43: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/harness.rs:53:15
  44: tokio::runtime::task::raw::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/raw.rs:113:5
  45: tokio::runtime::task::raw::RawTask::poll
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/raw.rs:70:18
  46: tokio::runtime::task::UnownedTask<S>::run
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/task/mod.rs:379:9
  47: tokio::runtime::blocking::pool::Inner::run
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/blocking/pool.rs:264:17
  48: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/bob/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.14.0/src/runtime/blocking/pool.rs:244:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by fominv** [comment]
I was also facing the same error message (`Multiplexed connection driver unexpectedly terminated`). Though, in my case it turned out to be an issue with the Alpine Docker (3.17) container that I was using. 

I am not completely sure here, but I had DNS issues in the Alpine container. Switching to Debian Bookworm fixed the issue for me. 

As a side note, the newest release of Alpine (3.18) implemented support for DNS lookups over TCP.

**Comment by nihohit** [comment]
fixed in https://github.com/redis-rs/redis-rs/pull/1035
